display_name: "Dataset Generator with Template Synthesizer"
key: "dataset-generator-template-synthesizer"
tags: ["Guides", "Dataset Generators"]
description: >
  This guide shows an example of a dataset generator that uses a Jinja template in the
  synthesizer.
long_description: !include README.md
