display_name: "Playground App"
key: "playground-app"
tags: ["Guides", "Dataset Generation"]
description: >
  This guide shows an example of a dataset generator that uses a Python script as the
  synthesizer.
long_description: !include "README.md"
