display_name: "Harry Potter Trivia"
key: "hp-trivia"
description: "Assesses the model knowledge of Harry Potter trivia."
config_spec:
  - key: "dataset_key"
    type: "dataset"
    display_name: "Dataset"
    default_value: "hp-trivia-dataset"
    description: "Dataset containing Harry Potter trivia questions and answers."
  - key: "judge_model_key"
    type: "model"
    display_name: "Judge Model"
    description: "Model used to judge whether the answer is correct."
definition:
  evaluated_entity_type: "model"
  dataset:
    key: "<< config.dataset_key >>"
  solver:
    type: "single_turn_solver"
    input_builder:
      type: "chat_completion"
      input_messages:
        - role: "system"
          content: "You are a helpful assistant."
        - role: "user"
          content: "Respond to this question concisely. {{ sample.question }}"
  scorers:
    - type: "model_as_a_judge_classifier"
      model_key: "<< config.judge_model_key >>"
      system_prompt: |
        You are a helpful assistant and rate whether the ground truth answer and the
        candidate answer are semantically the same. Semantically the same means that
        you do not care about small spelling mistakes, capitalization or whether
        additional information is given. This is all still considered correct.

        Respond only with 'correct' or 'incorrect' and nothing else.
      user_prompt: |
        Ground Truth Answer: {{ sample.gt_answer }}
        Candidate Answer: {{ trace.get_last_assistant_text() }}
      correct_labels:
        - "correct"
      incorrect_labels:
        - "incorrect"
      use_structured_outputs: true
