display_name: "OpenCode Model"
key: "model-opencode"
tags: ["Guides", "Models", "OpenCode"]
description: >
  This guide shows an example integration of an OpenCode agent.
long_description: !include README.md
