display_name: "Simple Instructions Following"
key: "simple-instructions-following"
description: "Evaluates how good the model is at following instructions."
config_spec:
  - display_name: "Ground Truth Option"
    key: "ground_truth"
    type: "string"
definition:
  dataset:
    key: "instructions-categorical-options"
  solver:
    type: "single_turn_solver"
    input_builder:
      type: "chat_completion"
      input_messages:
        - role: "user"
          content: >
            Example: If asked for first option in [A, B, C], correct response is: A.
            Example: If asked for last option in [A, B, C], correct response is: C.

            Instructions: The list of allowed responses is {{ sample.options }}. 
            Pick the << config.ground_truth >> option. No punctuation, quotes or 
            explanations.
  scorers:
    - type: "string_equals"
      ground_truth: >
        {{ sample.first if "<< config.ground_truth >>" == "first" else sample.last }}
