display_name: "RAG Context Relevancy"
key: "rag_context_relevancy"
description: >
  Evaluates the relevancy of retrieved contexts to a query. This evaluator considers 
  the query string and retrieved contexts.
evaluated_entity_type: "model"
config_spec:
  - type: "dataset"
    key: "qa_dataset"
    display_name: "QA Dataset"
  - type: "model"
    key: "judge_model"
    display_name: "Judge Model"
definition:
  dataset:
    key: "<< config.qa_dataset >>"
  solver:
    type: "single_turn_solver"
    input_builder:
      type: "chat_completion"
      input_messages:
        - role: "user"
          content: "{{ sample.question }}"
  scorers:
    - type: "model_as_a_judge_classifier"
      model_key: "<< config.judge_model >>"
      system_prompt: !include ./helpers/context_relevancy.txt
      user_prompt: >
        Information: {{ model_input.messages[-1].content }}
        Context: {{ model_output.choices[0].message.reference | map(attribute='content') | join('\n') }}
        Answer:
      correct_labels:
        - "YES"
      incorrect_labels:
        - "NO"
