display_name: "Job Factor Extraction Robustness"
key: "job-factor-extraction-robustness"
description: ""
evaluated_entity_type: "model"
config_spec:
  - key: "dataset"
    display_name: "Dataset"
    type: "dataset"
  - key: "dataset_column"
    display_name: "Dataset Column"
    type: "dataset_column"
definition:
  type: "declarative_task"
  dataset:
    key: "<< config.dataset >>"
  solver:
    type: "single_turn_solver"
    input_builder:
      type: "generic"
      template: |
        {"job_description": {{ sample.<< config.dataset_column >> | tojson }}}
  scorers:
    - key: "robustness"
      type: "python"
      compute_scores_snippet: !include ./helpers/job-factor-extraction-robustness-scorer.py
      metrics:
        - key: "robustness"
          type: "python"
          compute_metrics_snippet: !include ./helpers/job-factor-extraction-robustness-metric.py