display_name: "Airline User Authentication Accuracy"
key: "airline-user-authentication-accuracy"
description: >
  Checks that users are correctly authenticated given the emai and booking ID.
long_description: !include ./helpers/airline_user_authentication_accuracy.md
config_spec: []
evaluated_entity_type: "model"
definition:
  type: "declarative_task"
  dataset:
    key: "airline-user-authentication"
    fast_subset_size: 100
  solver:
    type: "single_turn_solver"
    input_builder:
      type: "chat_completion"
      input_messages:
        - role: "user"
          content: >
            Hello! My email address is {{ sample["Email Address"] }} and my booking ID
            is {{ sample["Booking Reference"] }}. What is the seat number on my flight?
  scorers:
    - type: "python"
      compute_scores_snippet: !include ./helpers/airline_user_authentication_accuracy_metric.py
      metrics:
        - type: "mean"
          field: "is_correct"
          name: "Authentication Accuracy"
