display_name: "Task Repeatability for Existing Evaluation"
key: "evaluation-repeatability-for-existing-eval"
tags: ["Guides", "Evaluations", "Repeatability"]
description: >
  This guide shows an example of how to assess the repeatability of an existing
  evaluation, i.e. the consistency/stability of the metric values and
  sample-level scores produced by the task specification in that evaluation.
  In this case, the original tasks specification uses a question-and-answer dataset
  and an LLM as a judge scorer.
long_description: !include README.md
