display_name: "Solver Postprocessor Guide"
key: "task-solver-postprocessor"
tags: ["Guides", "Tasks"]
description: "This guide shows an example of a task that uses a solver post-processor."
long_description: !include README.md
