display_name: "Python Metric"
key: "task-python-metric"
tags: ["Guides", "Tasks"]
description: >
  This guide shows an example of a Python scorer paired with a Python metric
  for custom per-sample scoring and custom cross-sample aggregation.
long_description: !include README.md
