display_name: "Playground App"
key: "playground-app"
tags: ["Guides", "Datasets", "Filters"]
description: >
  This guide shows an example integration of a dataset in JSONL format and how to filter it.
long_description: !include "README.md"
