display_name: "Dataset Generator with LLM Synthesizer"
key: "dataset-generator-llm-synthesizer"
tags: ["Guides", "Dataset Generators"]
description: >
  This guide shows an example of a dataset generator that uses an LLM as a synthesizer.
long_description: !include README.md
