display_name: "Task with Per-Sample Trials (Model Reliability)"
key: "task-with-trials"
tags: ["Guides", "Tasks", "Trials"]
description: >
  This guide shows an example of how to use per-sample trials in order to assess model
  reliability.
long_description: !include README.md
