display_name: "Playground App"
key: "playground-app"
tags: ["Guides", "Tasks"]
description: >
  This guide shows an example of how to use per-sample trials in order to assess model
  reliability.
long_description: !include README.md
