display_name: "Conversation Memory Evaluation"
key: "playground-app"
tags: ["General Purpose AI", "Tasks", "Models"]
description: >
  Evaluation of a chat model's ability to remember information from previous messages in
  the conversation.
long_description: !include "README.md"
