display_name: "Multi-turn Evaluation of Stateful Model Endpoint"
key: "evaluation-multiturn-stateful-responses"
tags: ["Guides", "Tasks", "Models"]
description: >
  Evaluation of a chat model's ability to remember information from previous messages in
  the conversation.
long_description: !include "README.md"
