display_name: "HuggingFace Dataset Filters"
key: "dataset-huggingface"
tags: ["Guides", "Datasets", "HuggingFace"]
description: >
  This guide shows an example integration of a dataset hosted by HuggingFace.
long_description: !include "README.md"
