display_name: "LangSmith Model"
key: "model-langsmith"
tags: ["Guides", "Models", "LangSmith"]
description: >
  This guide shows an example integration of a model hosted by LangSmith.
long_description: !include README.md
