display_name: "Playground App"
key: "playground-app"
tags: ["Guides", "Models"]
description: >
  This guide shows an example integration of OpenAI GPT-4.1 Nano integrated as a
  custom task model. Note, that this is not a demo example, GPT-4.1 is a chat completion
  model and is recommended to be integrated as a chat-completion task model.
long_description: !include "README.md"
