display_name: "Playground App"
key: "playground-app"
tags: ["Guides", "Models"]
description: >
  This guide shows an example integration of OpenAI GPT-4.1 Nano integrated as a 
  custom task.
long_description: !include "README.md"
