display_name: "HTTPS Enforcement System Task"
key: "system-task-enforces-https"
tags: ["Guides", "Tasks", "System Task"]
description: >
  This guide shows how to define and run a system task that checks a
  system's property (here whether it uses HTTPS).
long_description: !include "README.md"
