display_name: "System Task for HTTPS Enforcement"
key: "task-system-enforce-https"
tags: ["Guides", "Tasks", "System Task"]
description: >
  This guide shows how to define and run a system task that checks a
  system's property (here whether it uses HTTPS).
long_description: !include "README.md"
