display_name: "Evaluation of Model QA Knowledge"
key: "evaluation-qa-llm-scorer"
tags: ["Guides", "Evaluations"]
description: >
  This guide shows an example of how to evaluate the knowledge of a model on a specific
  topic. The evaluation uses a question-and-answer dataset and an LLM as a judge scorer.
long_description: !include README.md
