display_name: "Playground App"
key: "playground-app"
tags: ["Guides", "Datasets", "LangSmith"]
description: >
  This guide shows how to ingest traces from LangSmith as a dataset.
long_description: !include "README.md"
