display_name: "Enforces HTTPS"
key: "enforces-https"
description: "Checks whether a given URL enforces HTTPS by redirecting HTTP requests to HTTPS."
tags: ["Security"]
config_spec:
  - type: "string"
    key: "url"
    display_name: "URL"
    description: "The URL to check for HTTPS enforcement."
definition:
  type: "system_task"
  compute_evidence_snippet: !include "./enforce_https.py"
