display_name: "Playground App"
key: "playground-app"
tags: ["Guides", "Evaluations"]
description: >
  This guide shows an example of how to evaluate assess the repeatability of a task
  specification, i.e. assess the consistency/stability of the metric values and
  the sample-level scores it produces. In this case, the original tasks specification
  uses a question-and-answer dataset and an LLM as a judge scorer.
long_description: !include README.md
