name: validate-pr
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  validate-ticket-link:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - name: Check Jira Ticket Link
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Validating PR title: $TITLE"
          if [[ "$TITLE" =~ ^.*PE-[0-9]+[\)\,\ ].*$ ]]; then
            echo "PR title contains expected regex (Example: Add Feature X PE-123, PE-456)"
            exit 0
          elif [[ "$TITLE" =~ ^.*PE-[0-9]+$ ]]; then
            echo "PR title contains expected regex (Example: Add Feature X PE-123)"
            exit 0
          else
            echo "PR title MUST contain the link to the associated PE task. (Example: Add Feature X PE-123)"
            exit 1
          fi
  validate-semantic-pr-title:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - name: Check Semantic PR Title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
